<?
$scriptDuration = microtime(true) - $statistic['php']['start'];
$phpDuration = $scriptDuration - $statistic['sql']['duration'];
$phpDurationPercent = ceil($phpDuration/$scriptDuration*100);
$sqlDurationPercent = floor($statistic['sql']['duration']/$scriptDuration*100);
?>
<div class ="statistic">
    <span>[
    Time: <?=round($phpDuration, 4);?>s |
    PHP: <?=$phpDurationPercent?>%
    SQL: <?=$sqlDurationPercent?>% |
    SQL запросов: <?=$statistic['sql']['count']?> |
    SQL time: <?=round($statistic['sql']['duration'], 4);?>s
    ]</span>
</div>

</div>
</body>
</html>
